name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天凌晨 0 点自动执行
  workflow_dispatch: # 手动执行

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    # if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: run a standard checkout action
      - name: Checkout target repo
        uses: actions/checkout@v4

      # Step 2: run the sync action
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: dishao123/test # 上游仓库
          upstream_sync_branch: main # 上游分支
          target_sync_branch: main # 本地分支
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 使用 Github 自带的 Token 来执行任务
          git_config_user: github-actions[bot] # 使用机器人账号完成同步
          git_config_email: github-actions[bot]@users.noreply.github.com # 机器人邮箱

          # 关闭测试模式
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] 由于出现未知错误，本次同步失败。"
          exit 1